#!/usr/bin/expect -f
set type [lindex $argv 0]
set user [lindex $argv 1]
set host [lindex $argv 2]
set password_or_pem_path [lindex $argv 3]
set port [lindex $argv 4]
set timeout -1

switch $type {
    pwd {
        spawn ssh -o StrictHostKeyChecking=no -p$port $user@$host
        expect "*assword:*"
        send "$password_or_pem_path\r"
    }
    key {
        spawn ssh -o StrictHostKeyChecking=no -i $password_or_pem_path  -p$port $user@$host
    }
}

interact